define USER_NAME = &&1
define DEFAULT_TBS = &&2

alter session set "_ORACLE_SCRIPT"=true;

CREATE USER &&USER_NAME
  IDENTIFIED BY oracle
  DEFAULT TABLESPACE &&DEFAULT_TBS
  TEMPORARY TABLESPACE temp
    QUOTA 20M on &&DEFAULT_TBS;


