

SET TIME ON
SET TIMING ON
PROMPT Enter username
DEFINE USER_NAME = &&1
PROMPT Enter tablespace_name
DEFINE TABLESPACE_NAME = &&2

SPOOL DROP_SCHEMA.LOG

SET SERVEROUTPUT ON
PROMPT
PROMPT Username caling to drop_schema: &&USER_NAME
PROMPT

@drop_schema.sql &&USER_NAME

PROMPT
PROMPT Username caling to drop_tablspaces: &&TABLESPACE_NAME
PROMPT

@drop_tablespaces.sql &&TABLESPACE_NAME

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME
UNDEFINE TABLESPACE_NAME

SPOOL OFF