<#macro footer>
    <footer class="page-footer font-small stylish-color-dark pt-4">
        <div class="container mx-auto text-center">
            <div class="container text-center text-md-left">
                <div class="row">
                    <div class="col-md-4 mx-auto">
                        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Just Book</h5>
                        <p>some text some text some text some text some text some text some text some text some text</p>
                    </div>
                    <!-- Grid column -->
                    <hr class="clearfix w-100 d-md-none" />
                    <!-- Grid column -->
                    <div class="col-md-2 mx-auto">
                        <!-- Links -->
                        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>
                        <ul class="list-unstyled">
                            <li>
                                <a href="#">Contacts page</a>
                            </li>
                            <li>
                                <a href="/restaurant">Book Restaurants</a>
                            </li>
                            <li>
                                <a href="/cafe">Cafes</a>
                            </li>
                        </ul>
                    </div>
                    <!-- Grid column -->
                    <hr class="clearfix w-100 d-md-none"/>
                    <!-- Grid column -->
                    <hr class="clearfix w-100 d-md-none"/>
                    <!-- Grid column -->
                    <div class="col-md-2 mx-auto">
                        <!-- Links -->
                        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Partners</h5>
                        <ul class="list-unstyled">
                            <li>
                                <a href="#" target="_blank">Relax</a>
                            </li>
                            <li>
                                <a href="#" target="_blank">Brioche</a>
                            </li>
                            <li>
                                <a href="#" target="_blank">O.D.I</a>
                            </li>
                            <li>
                                <a href="#" target="_blank">SomeText</a>
                            </li>
                        </ul>
                    </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row -->
            </div>
            <!-- Footer Links -->
        </div>
    </footer>
</#macro>