DEFINE SCHEMA_NAME = &&1
DEFINE SCHEMA_PASSWORD = &&2
DEFINE DEFAULT_TABLESPACE = &&3

CREATE USER &&SCHEMA_NAME
 IDENTIFIED BY &&SCHEMA_PASSWORD
 DEFAULT TABLESPACE &&DEFAULT_TABLESPACE
 TEMPORARY TABLESPACE temp
 QUOTA UNLIMITED on &&DEFAULT_TABLESPACE;

UNDEFINE SCHEMA_PASSWORD;
UNDEFINE DEFAULT_TABLESPACE;