DEFINE SCHEMA_NAME = &&1

GRANT CREATE SESSION TO &&SCHEMA_NAME;
GRANT CREATE TABLE TO &&SCHEMA_NAME;
GRANT CREATE PROCEDURE, CREATE VIEW, CREATE SEQUENCE TO &&SCHEMA_NAME;
GRANT CREATE TRIGGER TO &&SCHEMA_NAME;

UNDEFINE SCHEMA_NAME;