CREATE TABLE CONSTRUCTOR (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    NAME VARCHAR2(200),
    WINS NUMBER,
    CONSTRAINT PK_CONSTRUCTOR PRIMARY KEY (ID) ENABLE
);

COMMENT ON COLUMN CONSTRUCTOR.ID IS 'Unique identifier';
COMMENT ON COLUMN CONSTRUCTOR.NAME IS 'Constructor team name';
COMMENT ON COLUMN CONSTRUCTOR.WINS IS 'Number of wins';

