DEFINE USER_NAME = &&1
DEFINE INDEX_TABLESPACE = '&&USER_NAME._IDX'

ALTER TABLE SEASON_EVENT ADD CONSTRAINT FK_SEASON_EVENT_SEASON FOREIGN KEY (SEASON_ID) REFERENCES SEASON(ID) ON DELETE CASCADE;
CREATE INDEX FK_SEASON_EVENT_SEASON_INDEX ON SEASON_EVENT(SEASON_ID) TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE SEASON_EVENT ADD CONSTRAINT FK_SEASON_EVENT_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID) ON DELETE CASCADE;
CREATE INDEX FK_SEASON_EVENT_EVENT_INDEX ON SEASON_EVENT(EVENT_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE EVENT ADD CONSTRAINT FK_EVENT_CIRCUIT FOREIGN KEY (CIRCUIT_ID) REFERENCES CIRCUIT(ID) ON DELETE SET NULL;
CREATE INDEX FK_EVENT_CIRCUIT_INDEX ON EVENT(CIRCUIT_ID) TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE EVENT ADD CONSTRAINT FK_EVENT_WINNER FOREIGN KEY (WINNER_ID) REFERENCES DRIVER(ID) ON DELETE SET NULL;
CREATE INDEX FK_EVENT_WINNER_INDEX ON EVENT(WINNER_ID) TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE EVENT ADD CONSTRAINT FK_EVENT_POLE FOREIGN KEY (POLE_POSITION_ID) REFERENCES DRIVER(ID) ON DELETE SET NULL;
CREATE INDEX FK_EVENT_POLE_INDEX ON EVENT(POLE_POSITION_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE EVENT_DRIVER ADD CONSTRAINT FK_EVENT_DRIVER_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID) ON DELETE CASCADE;
CREATE INDEX FK_EVENT_DRIVER_EVENT_INDEX ON EVENT_DRIVER(EVENT_ID) TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE EVENT_DRIVER ADD CONSTRAINT FK_EVENT_DRIVER_DRIVER FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER(ID) ON DELETE CASCADE;
CREATE INDEX FK_EVENT_DRIVER_DRIVER_INDEX ON EVENT_DRIVER(DRIVER_ID) TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE EVENT_DRIVER ADD CONSTRAINT FK_EVENT_DRIVER_CONSTRUCTOR FOREIGN KEY (CONSTRUCTOR_ID) REFERENCES CONSTRUCTOR(ID) ON DELETE CASCADE;
CREATE INDEX FK_EVENT_DRIVER_CONSTRUCTOR_INDEX ON EVENT_DRIVER(CONSTRUCTOR_ID) TABLESPACE &&INDEX_TABLESPACE;

UNDEFINE USER_NAME
UNDEFINE INDEX_TABLESPACE
