CREATE TABLE CIRCUIT (
    id number generated always as identity increment by 1 start with 1 minvalue 1 not null,
    NAME VARCHAR2(100),
    DISTANCE NUMBER,
    LATITUDE NUMBER,
    LONGITUDE NUMBER,
    COUNTRY VARCHAR2(100),
    CITY VARCHAR2(100),
    CONSTRAINT PK_TRACK PRIMARY KEY (ID) ENABLE
);

COMMENT ON COLUMN CIRCUIT.ID IS 'Unique identifier';
COMMENT ON COLUMN CIRCUIT.NAME IS 'Circuit name';
COMMENT ON COLUMN CIRCUIT.DISTANCE IS 'Circuit distance';
COMMENT ON COLUMN CIRCUIT.LATITUDE IS 'Circuit latitude';
COMMENT ON COLUMN CIRCUIT.LONGITUDE IS 'Circuit longitude';
COMMENT ON COLUMN CIRCUIT.COUNTRY IS 'Contry where circuit is located';
COMMENT ON COLUMN CIRCUIT.CITY IS 'City where circuit is located';

