CREATE TABLE SEASON (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    NAME VARCHAR2(100),
    CONSTRAINT PK_SEASON PRIMARY KEY (ID) ENABLE
);

COMMENT ON COLUMN SEASON.ID IS 'Unique identifier';
COMMENT ON COLUMN SEASON.NAME IS 'Season name';