define SCHEMA_NAME = &&1
define SCHEMA_PASSWORD = &&2
define DEFAULT_TBS = &&3

alter session set "_ORACLE_SCRIPT"=true;

CREATE USER &&SCHEMA_NAME
  IDENTIFIED BY &&SCHEMA_PASSWORD
  DEFAULT TABLESPACE &&DEFAULT_TBS
  TEMPORARY TABLESPACE temp
    QUOTA 20M on &&DEFAULT_TBS;


