DEFINE USER_NAME = &&1

DEFINE TABLESPACE_NAME = '&&USER_NAME._DATA'
DEFINE INDEX_NAME = '&&USER_NAME._IDX'

DROP TABLESPACE "&&TABLESPACE_NAME"
    INCLUDING CONTENTS AND DATAFILES
     CASCADE CONSTRAINTS;
	 
DROP TABLESPACE "&&INDEX_NAME"
    INCLUDING CONTENTS AND DATAFILES
     CASCADE CONSTRAINTS;
	 
UNDEFINE TABLESPACE_NAME
UNDEFINE INDEX_NAME